### ISSUE TITLE
infografia actividad 1 biblioteca dll

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/infografia-de-las-librerias-Arnold-Js#2]
[infografia dll.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Arnold-Js/files/8217612/infografia.dll.pdf)

**Comment by IrvingFernand0** [comment]
Esta práctica obtuvo 100% 
Correspondiente a **20** de calificación

**Comment by josealfredo79** [comment]
bien hecho y revisado...
